version: '3'
services:  
  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - ${DB_PORT}:3306
  #     # - "${CLIENT_PORT}:${INTERNAL_PORT}"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_TCP_PORT: ${DB_PORT}
  db:
    image: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
  celery:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 8090:15672
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}