# Generated by Django 3.1.3 on 2020-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'verbose_name': 'dollar',
                'verbose_name_plural': 'dollars',
            },
        ),
        migrations.CreateModel(
            name='Udi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'verbose_name': 'udi',
                'verbose_name_plural': 'udis',
            },
        ),
        migrations.AddConstraint(
            model_name='udi',
            constraint=models.UniqueConstraint(fields=('date', 'value'), name='udi_date_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='dollar',
            constraint=models.UniqueConstraint(fields=('date', 'value'), name='dollar_date_value_unique'),
        ),
    ]
