# Generated by Django 3.1.3 on 2020-11-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'verbose_name': 'dollar',
                'verbose_name_plural': 'dollars',
            },
        ),
        migrations.CreateModel(
            name='Udi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'verbose_name': 'udi',
                'verbose_name_plural': 'udis',
            },
        ),
    ]
